### ISSUE TITLE
patch_pystache should run 2to3

### ISSUE THREAD

**Issue by telotortium** [kerrickstaley/Chinese-Prestudy#19] opened 2020-11-02 18:27 UTC
Two recent issues, #16 and #17, were caused by Python 3 incompatibilities with Python 2. I believe that pystache's Python 3 support is meant to come via `2to3` being run on the Python 2 code, from [this comment](https://github.com/defunkt/pystache/blob/ebdc702f73b1df630a720a5b97d3d882b5a6c8e7/pystache/common.py#L17): 'The latter evaluates to "bytes" in Python 3 -- even after conversion by 2to3.' Rather than continue to individually patch these issues as they come up, `2to3` should be run on pystache first, and only then should individual patches be made. I believe `2to3` will fix both #16 and #17 without any other patching needed.

**Comment by kerrickstaley** [comment] 2020-11-03 07:04
Yep, you're correct; when you install pystache in a Python 3 environment via pip, pip will run 2to3 on the code before installation. This is configured with `setup.py`'s `use_2to3` option; the code that does that is [here](https://github.com/defunkt/pystache/blob/master/setup.py#L359).

Because we're not installing pystache in the normal way, but simply copying the code, we need to run `2to3` ourselves.

I've pushed 569c0019def10b6d8899fd7cf09e35b4eb409dfc which runs `2to3` on the pystache code before copying it into `package.ankiaddon`. I've also uploaded a new version of the package to Ankiweb.

Could you help me test out the new version of Chinese Prestudy? I can't seem to reproduce this issue in my local Anki install.

**Comment by telotortium** [comment] 2020-11-03 07:13
Yes, this works for me. Thanks for the quick response!

**Comment by kerrickstaley** [comment] 2020-11-03 07:15
Awesome! I also figured out why the issue wasn't reproing locally, and confirmed that I encounter this issue on f5103b08f37684f41b4f89b1ef164b76d1a37cbb (`master^`) but not on 569c0019def10b6d8899fd7cf09e35b4eb409dfc (`master`). Closing.

**Closed as completed by kerrickstaley** 2020-11-03 07:15 UTC
