### ISSUE TITLE
UnicodeDecodeError - codec can't decode byte 0x81 in position 248

### ISSUE THREAD

**Issue by liquiddandruff** [kerrickstaley/Chinese-Prestudy#4] opened 2018-09-05 07:54 UTC
Really cool idea!

I tried it out with some Chinese text but it gave me the following stack trace.

I realized after pasting anything like even `asdf` in the "Paste in the chinese text you want to read" screen errors with the same stack trace as follows:

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.3 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\__init__.py", line 75, in <lambda>
    continue_button.clicked.connect(lambda: self.text_entry_continue_action())
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\__init__.py", line 89, in text_entry_continue_action
    self.show_words_window()
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\__init__.py", line 155, in show_words_window
    self.update_words_and_defs_table()
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\__init__.py", line 167, in update_words_and_defs_table
    words_to_study = self.words_to_study
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\__init__.py", line 175, in words_to_study
    return self.get_words_to_study(self.word_target)
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\__init__.py", line 189, in get_words_to_study
    words = [w for w in self.all_words_to_study[:target] if w is not None]
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\__init__.py", line 209, in all_words_to_study
    return [w if {w.simp, w.trad} & unknown_words_set else None for w in self.vocab_list.words]
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\__init__.py", line 270, in vocab_list
    return chinese_vocab_list.VocabList.load()
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\chinese_vocab_list\__init__.py", line 105, in load
    words = [VocabWord.from_dict(d) for d in yaml.load(h)]
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\yaml\__init__.py", line 70, in load
    loader = Loader(stream)
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\steven\AppData\Roaming\Anki2\addons21\882364911\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\Users\dae\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
<class 'UnicodeDecodeError'>: 'charmap' codec can't decode byte 0x81 in position 248: character maps to <undefined>
```

**Comment by kerrickstaley** [comment] 2018-09-05 18:29
Another user also reported the same issue. I'll take a look tonight and get
back to you.

Thanks for trying the tool and providing feedback!

**Comment by applantation** [comment] 2018-09-06 01:03
I have the same error. This happens both if I copy a text from the clipboard on OSX and even if I just type in 你好 into the text field. 

It obviously has nothing to do with my input, it happens when initializing the app, reading in the vocabulary. 

> Debug info:
> Anki 2.1.3 Python 3.6.1 Qt 5.9.2 PyQt 5.9
> Platform: Mac 10.13.6
> Flags: frz=True ao=True sv=1
> 
> Caught exception:
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 75, in <lambda>
>     continue_button.clicked.connect(lambda: self.text_entry_continue_action())
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 89, in text_entry_continue_action
>     self.show_words_window()
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 155, in show_words_window
>     self.update_words_and_defs_table()
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 167, in update_words_and_defs_table
>     words_to_study = self.words_to_study
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 175, in words_to_study
>     return self.get_words_to_study(self.word_target)
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 189, in get_words_to_study
>     words = [w for w in self.all_words_to_study[:target] if w is not None]
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/cached_property.py", line 35, in __get__
>     value = obj.__dict__[self.func.__name__] = self.func(obj)
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 209, in all_words_to_study
>     return [w if {w.simp, w.trad} & unknown_words_set else None for w in self.vocab_list.words]
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/cached_property.py", line 35, in __get__
>     value = obj.__dict__[self.func.__name__] = self.func(obj)
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 270, in vocab_list
>     return chinese_vocab_list.VocabList.load()
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/chinese_vocab_list/__init__.py", line 105, in load
>     words = [VocabWord.from_dict(d) for d in yaml.load(h)]
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/yaml/__init__.py", line 70, in load
>     loader = Loader(stream)
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/yaml/loader.py", line 34, in __init__
>     Reader.__init__(self, stream)
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/yaml/reader.py", line 85, in __init__
>     self.determine_encoding()
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/yaml/reader.py", line 124, in determine_encoding
>     self.update_raw()
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/yaml/reader.py", line 178, in update_raw
>     data = self.stream.read(size)
>   File "/Users/dae/Local/py59/lib/python3.6/encodings/ascii.py", line 26, in decode
> <class 'UnicodeDecodeError'>: 'ascii' codec can't decode byte 0xe7 in position 8: ordinal not in range(128)

**Comment by applantation** [comment] 2018-09-06 01:17
I think the solution might just be to open the yaml file with the codec specified, something like this
with codecs.open(VOCAB_FILE, 'r', 'utf-8') as h:

I do not know how to rebuild the project, so I cannot test this.

**Comment by kerrickstaley** [comment] 2018-09-06 06:20
I've pushed an update that I believe fixes this issue. It was exactly the change that @applantation suggested; thanks! https://github.com/kerrickstaley/Chinese-Vocab-List/commit/f0f72f30c6a36e4631ffb1e738c6d98d032b22ef

Please update the addon and let me know if the issue is resolved for you! (Go into Anki, Tools > Add-ons > Check for Updates, then after updating restart Anki).

**Comment by applantation** [comment] 2018-09-07 01:03
I can confirm this fixes this error. 
But then a bit further down a similar error occurs (as they are related I am not opening a new issue)

> Anki 2.1.3 Python 3.6.1 Qt 5.9.2 PyQt 5.9
> Platform: Mac 10.13.6
> Flags: frz=True ao=True sv=1
> 
> Caught exception:
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 162, in <lambda>
>     continue_button.clicked.connect(lambda: self.words_window_continue_action())
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 284, in words_window_continue_action
>     print(self.input_with_hard_words_annotated)
> <class 'UnicodeEncodeError'>: 'ascii' codec can't encode character '\u8fdb' in position 3: ordinal not in range(128)

This probably gives the answer to the problem:
https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

**Comment by ghost** [comment] 2018-09-08 08:08
Following error while trying to import text
Anki 2.1.4 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\aj198\AppData\Roaming\Anki2\addons21\882364911\__init__.py", line 318, in <lambda>
    self.finish_button.clicked.connect(lambda: self.add_notes_action())
  File "C:\Users\aj198\AppData\Roaming\Anki2\addons21\882364911\__init__.py", line 334, in add_notes_action
    add_notes(self.vocab_words, self.combo_box.currentText(), self.tags_box.text().split())
  File "C:\Users\aj198\AppData\Roaming\Anki2\addons21\882364911\__init__.py", line 348, in add_notes
    out_deck = chineseflashcards.ChineseDeck(deck['id'], deck_name)
  File "C:\Users\aj198\AppData\Roaming\Anki2\addons21\882364911\chineseflashcards\__init__.py", line 312, in __init__
    self._cedict = load_cedict()
  File "C:\Users\aj198\AppData\Roaming\Anki2\addons21\882364911\chineseflashcards\__init__.py", line 260, in load_cedict
    for line in inf:
<class 'UnicodeDecodeError'>: 'cp932' codec can't decode byte 0x87 in position 795: illegal multibyte sequence

**Comment by applantation** [comment] 2018-09-09 00:53
Yes, latest commit takes us one step further, again the same problem as already reported above.

> Debug info:
> Anki 2.1.3 Python 3.6.1 Qt 5.9.2 PyQt 5.9
> Platform: Mac 10.13.6
> Flags: frz=True ao=True sv=1
> 
> Caught exception:
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 318, in <lambda>
>     self.finish_button.clicked.connect(lambda: self.add_notes_action())
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 334, in add_notes_action
>     add_notes(self.vocab_words, self.combo_box.currentText(), self.tags_box.text().split())
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 348, in add_notes
>     out_deck = chineseflashcards.ChineseDeck(deck['id'], deck_name)
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/chineseflashcards/__init__.py", line 312, in __init__
>     self._cedict = load_cedict()
>   File "/Users/ludwig/Library/Application Support/Anki2/addons21/882364911/chineseflashcards/__init__.py", line 260, in load_cedict
>     for line in inf:
>   File "/Users/dae/Local/py59/lib/python3.6/encodings/ascii.py", line 26, in decode
> <class 'UnicodeDecodeError'>: 'ascii' codec can't decode byte 0xe4 in position 781: ordinal not in range(128)

**Comment by ludwigb** [comment] 2018-09-09 08:49
I can confirm that the latest fix to the chineseflashcards repo fixed this issue. 
Thanks for the effort.

**Comment by kerrickstaley** [comment] 2018-09-10 17:14
Good to hear :) Closing this issue.

**Closed as completed by kerrickstaley** 2018-09-10 17:14 UTC
